name: Automate VM and Check the Disk Info

on:   
 
 push:
   branches: 
       - main

jobs:
  azure-login:
      name: Login to azure
      runs-on: self-hosted
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4 

        - name: Login to Azure
          run: az login --use-device-code

        - name: Check the Azure Account
          run: az account show

        - name: Checking Resources in Resource Group
          run: |
           az resource list --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --output table
  
  checking-azure-vm:
      name: checking VM
      runs-on: self-hosted
      needs: [azure-login]
      steps:
        - name: Checking the VM
          run: |
           az vm show --name ${{ secrets.AZURE_VM_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query "id" --output tsv && echo "VM exists" || echo "VM does not exist"

        - name: checking the Power-State of the VM
          run: |
           az vm show --name ${{ secrets.AZURE_VM_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --query "powerState" --output tsv \
              | grep "stopped" && az vm start --name ${{ secrets.AZURE_VM_NAME }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} && echo "VM started" || echo "VM is already running"

        - name: Checking the Nginx in VM
          run: |
           az vm run-command invoke \
           --command-id RunShellScript \
           --name ${{ secrets.AZURE_VM_NAME }} \
           --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
           --scripts "sudo apt update -y && (dpkg -l | grep -qw nginx && echo 'Nginx is already installed' || (sudo apt install -y nginx && sudo systemctl enable nginx && sudo systemctl start nginx && echo 'Nginx installed'))"


  